<?xml version="1.0" encoding="utf-8"?><Database Name="OAI_ShippingRequest" Class="ShippingRequestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=aag-omni;Initial Catalog=OAI_ShippingRequest;Integrated Security=True" SettingsObjectName="ImprovedShipper.Properties.Settings" SettingsPropertyName="OAI_ShippingRequestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ISO3166_Countries" Member="ISO3166_Countries">
    <Type Name="ISO3166_Country">
      <Column Name="ISO3166_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IATA_Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Political_Subunits" Member="Political_Subunits">
    <Type Name="Political_Subunit">
      <Column Name="IATA_Code" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Political_Unit_Name" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Political_Unit_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Processed_Requests" Member="Processed_Requests">
    <Type Name="Processed_Request">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Total_Cost" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Tracking_Num" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="To_Company" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="To_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_AddOne" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_AddTwo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="To_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="From_SamName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="From_EmpID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ship_InitDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Original_ShipID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Payroll_Status" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ship_Type" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shipping_Request" Member="Shipping_Requests">
    <Type Name="Shipping_Request">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ship_Type_Business_Private" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ShipInitatingDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="InitiatingDepartment" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="From_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Company" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Address_One" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Address_Two" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="From_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Shipped_By_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Shipped_By_Time" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="Signature_Required" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Bill_To_Third_Party" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Logged_In_User" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="From_Email_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Country" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="To_Postal_Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Urgency" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Employee_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Shipping_Request_Shipping_Item" Member="Shipping_Items" ThisKey="ID" OtherKey="ID" Type="Shipping_Item" />
    </Type>
  </Table>
  <Table Name="dbo.Shipping_Items" Member="Shipping_Items">
    <Type Name="Shipping_Item">
      <Column Name="Ship_Item_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Tracking_Number" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Item_Cost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Processed_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Shipping_Request_Shipping_Item" Member="Shipping_Request" ThisKey="ID" OtherKey="ID" Type="Shipping_Request" IsForeignKey="true" />
    </Type>
  </Table>
</Database>